# Generated by Django 3.1.3 on 2021-06-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210615_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment2',
            name='review',
        ),
        migrations.AddField(
            model_name='comment2',
            name='forest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.forest'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
