# Generated by Django 3.1.3 on 2021-06-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210616_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment2',
            name='forest',
        ),
    ]
