# Generated by Django 3.1.3 on 2021-06-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
